fix: using role and user data sources panics
```
❯ cat roles.tf
data "zedcloud_role" "controller_role_sysmanager" {
  name  = "ControllerSysManager_TF_2nd"
  title = ""
  type  = ""
  state = ""
  scopes {
    enterprise_filter = []
    project_filter    = []
  }
}

data "zedcloud_role" "controller_role_admin" {
  name  = "ControllerAdmin_TF_2nd"
  title = ""
  type  = " "
  state = ""
  scopes {
    enterprise_filter = []
    project_filter    = []
  }
}

output "role_details_sysmanager" {
  value       = indent(2, jsonencode(zedcloud_role.controller_role_sysmanager))
  description = "Details of the controller_role_sysmanager role as JSON"
}

output "role_details_admin" {
  value       = indent(2, jsonencode(zedcloud_role.controller_role_admin))
  description = "Details of the controller_role_admin role as JSON"
}

❯ tofu apply
data.zedcloud_role.controller_role_admin: Reading...
data.zedcloud_role.controller_role_sysmanager: Reading...
zedcloud_role.controller_role_admin: Refreshing state... [id=AAGFABDWJVZPTHFAw4sViWfokS_-]
zedcloud_role.controller_role_sysmanager: Refreshing state... [id=AAGFABAelKdwRoZAA68rKFXwOsCI]
╷
│ Error: Plugin did not respond
│
│   with zedcloud_role.controller_role_sysmanager,
│   on roles.tf line 1, in resource "zedcloud_role" "controller_role_sysmanager":
│    1: resource "zedcloud_role" "controller_role_sysmanager" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with zedcloud_role.controller_role_admin,
│   on roles.tf line 17, in resource "zedcloud_role" "controller_role_admin":
│   17: resource "zedcloud_role" "controller_role_admin" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with data.zedcloud_role.controller_role_sysmanager,
│   on roles.tf line 34, in data "zedcloud_role" "controller_role_sysmanager":
│   34: data "zedcloud_role" "controller_role_sysmanager" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with data.zedcloud_role.controller_role_admin,
│   on roles.tf line 46, in data "zedcloud_role" "controller_role_admin":
│   46: data "zedcloud_role" "controller_role_admin" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-zedcloud_v2.3.1-rc1.dev.main.f7fd733 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xad0c78]

goroutine 51 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0007e5960, {0x14e5d28, 0xc000e50a50}, 0xc001508480, {0x1133060, 0xc000b387e0})
	/home/ev-zed1/ZED/git/github.com/zededa/terraform-provider-zedcloud/v2/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:724 +0xf8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0007e5960, {0x14e5d28, 0xc000e50a50}, 0xc001508380, {0x1133060, 0xc000b387e0})
	/home/ev-zed1/ZED/git/github.com/zededa/terraform-provider-zedcloud/v2/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:943 +0x127
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc0001a23f0, {0x14e5d28?, 0xc000e50990?}, 0xc000e0a0e0)
	/home/ev-zed1/ZED/git/github.com/zededa/terraform-provider-zedcloud/v2/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:1179 +0x346
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc0004503c0, {0x14e5d28?, 0xc000e50180?}, 0xc0014680f0)
	/home/ev-zed1/ZED/git/github.com/zededa/terraform-provider-zedcloud/v2/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:658 +0x3c4
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x12f1a60, 0xc0004503c0}, {0x14e5d28, 0xc000e50180}, 0xc000258070, 0x0)
	/home/ev-zed1/ZED/git/github.com/zededa/terraform-provider-zedcloud/v2/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001503c0, {0x14eb200, 0xc000d54000}, 0xc000e06000, 0xc000b00570, 0x203cff0, 0x0)
	/home/ev-zed1/ZED/git/github.com/zededa/terraform-provider-zedcloud/v2/vendor/google.golang.org/grpc/server.go:1335 +0xdb3
google.golang.org/grpc.(*Server).handleStream(0xc0001503c0, {0x14eb200, 0xc000d54000}, 0xc000e06000, 0x0)
	/home/ev-zed1/ZED/git/github.com/zededa/terraform-provider-zedcloud/v2/vendor/google.golang.org/grpc/server.go:1712 +0x9cc
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/home/ev-zed1/ZED/git/github.com/zededa/terraform-provider-zedcloud/v2/vendor/google.golang.org/grpc/server.go:947 +0xaf
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 40
	/home/ev-zed1/ZED/git/github.com/zededa/terraform-provider-zedcloud/v2/vendor/google.golang.org/grpc/server.go:958 +0x133

Error: The terraform-provider-zedcloud_v2.3.1-rc1.dev.main.f7fd733 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```